name: Goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  # Name of module and id separated by a slash
  INSTANCE: Writerside/hi
  # Replace XX with the ID of the instance in capital letters
  ARTIFACT: webHelpHI2-all.zip
  # Docker image version
  DOCKER_VERSION: 232.10275
  # Add the variable below to upload Algolia indexes
  # Replace HI with the ID of the instance in capital letters
  ALGOLIA_ARTIFACT: algolia-indexes-HI.zip

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write
  pages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Get tags
        run: git fetch --force --tags

      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4

      -
        name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean ${{ github.event_name == 'workflow_dispatch' && '--snapshot' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
